### PR TITLE
Backport Aether 1.5 compat (1.20.1)

### LINKED ISSUE #205: Crash on clicking singleplayer.
Title, crash report contains modlist.

https://pastebin.com/8ScCR8zi

### LINKED ISSUE #206: crash when clicking create new world
[crash-2024-10-06_20.26.04-client.txt](https://github.com/user-attachments/files/17271409/crash-2024-10-06_20.26.04-client.txt)

Everything fixed itself when I removed ancient aether or downgraded the original aether mod to 1.4.2

### LINKED ISSUE #207: Crashed
I decide to play with this mods but game suddenly crashed for use latest version of The Aether & Aether Redux
Aether 1.5.1 & Aether Redux 2.0.18
Crash report detail:
[crash-2024-11-13_17.01.54-client.txt](https://github.com/user-attachments/files/17730440/crash-2024-11-13_17.01.54-client.txt)

### LINKED ISSUE #208: Crash when creating a world
So I have a custom modpack and wanna try out the mod but trying to create a new world is causing this crash. The crash report is saying Ancient Aether is causing it, but I wanna know if this can be fixed without having to remove the mod.
[crash-2024-11-17_11.35.00-client.txt](https://github.com/user-attachments/files/17791782/crash-2024-11-17_11.35.00-client.txt)
[latest.log](https://github.com/user-attachments/files/17791783/latest.log)

### PR DESCRIPTION
**Pull request by VoidLeech**
Hi! As you're aware, Aether 1.5 introduced an incompatibility with Ancient Aether which you fixed with your 1.20.4 release.

As Aether 1.5 is also available for 1.20.1 and this crash prevents creating or loading worlds, I figured a hotfix for this version would be nice to have, so I've backported 2ca8f1baa46167bbc6d22e1347b2855c5c795916 (:
This PR already bumps the version number. (Some version number bumps seen on modrinth/cf seem to be missing from the repo even though the fixes from those bumps is there)
To merge, you just have to make a new branch starting from dee944d4f203716ae6988d5c348a82452da30745 and have this PR point at that branch instead. 

Fixes #205
Fixes #206 
Fixes #207 
Fixes #208

I wanted to quickly make a PR for 1.19.4 (brancing off of 2644ab0b9b646aa027694b97aa80ac9ada5ea152) as well but that additionally runs into some compilation issues for the Ancient Guardian when updating the Aether deps and I don't have the time to dive into that right now.

### CODE REVIEW

**Comment by Builderdog841** [comment]
Oh sorry haven't seen this because I'm currently busy with other things and also working on other mods like Aether II but thanks for the fixes. I'll try to merge them asap

**Comment by Builderdog841** [comment]
Unfortunately it seems like there is some sort of error in the pr since trying to run gradle after I merged it into the new 1.20.1x Branch results an immediat gradle error that I am unaware on how to fix.

```
Could not open init generic class cache for initialization script 'C:\Users\Username\AppData\Local\Temp\wrapper_init.gradle' (C:\Users\Username\.gradle\caches\8.0\scripts\9jer43gnna3hamxmat6lgifa6).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65
```

This is the crash, and all the information I can provide unfortunately since there aren't gradle logs to my knowledge. I might look into backporting the changes myself if I find the time for it

**Comment by VoidLeech** [comment]
I think you are using java > 17?

**Comment by Builderdog841** [comment]
Oh right, didn't think about that. Thanks, I'll look into it tomorrow

**Comment by VoidLeech** [comment]
Hi, have you made any progress? (:

**Comment by Builderdog841** [comment]
Oh sorry I've been incredibly busy recently hope I can find time before christmas

**Comment by RaixuStuff** [comment]
I'm just reminding you about this just in case you forgot!

**Comment by Yoshiman5551** [comment]
PLEASE MERGE THIS

**Comment by ITLSupress** [comment]
I just built this pull and tried it on my server, works like a charm.

**Comment by Builderdog841** [comment]
I though I already merged it and just didn't compile yet. I should find time to look into this very soon. Just gonna note that I'm not really working on the project atm since I have recently become an Aether Ii developer that's why it hasn't been a priority.

**Comment by VoidLeech** [comment]
At the very least you did a local merge yeah, but were using the wrong java version afaict. Anyway, good to hear and yeah with that I wouldn’t be expecting a lot of maintenance here (:

**Comment by Builderdog841** [comment]
okay pr has now been publicly merged in form of 1.20.x branch, and I have added you to the credits, I'll try backport some of the QoL changes from the 1.20.4 and you can expect a public release either later today or tomorrow

**Pull request closed without merging**
